name: ArmTTK on pull request

on: [pull_request]

jobs:
  armttk:
    name: runner / armttk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: ./iac/deploy.bicep
          outputFilePath: ./iac/deploy.json
      - uses: microsoft/action-armttk@0.0.5
        with:
          # github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          glob_pattern: "./iac/**/*.json"
