name: ArmTTK on pull request

on: [pull_request]

jobs:
  armttk:
    name: runner / armttk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/action-armttk@0.0.5
        with:
          # github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          bicepFile: deploy.bicep
          workdir: ./iac
